### ISSUE TITLE
Shell pipeline comments

### ISSUE THREAD

**Issue by beroe** [swcarpentry/DEPRECATED-guide#2]
Looks very nice! Comments below...
- I don't resent you implying that gelatinous animals are "goo". Not at all.
- The disclaimer at the beginning seems too prominent relative to other info. (Of course we still need the shell! ;^) As shown in Figure 1, it never goes out of style.
- Seems weird to switch from Nelle to vlad in the discussion, but maybe it works in the sense of "now we will return to Nelle's original problem". 
- The "orthogonality" call out box doesn't make anything clearer for me. You say it doesn't belong to `ls`, but then give an example using `ls`... maybe an example using cd would be clearer? The explanation "meanings of the parts are the same no matter how they are combined" seems more clearly illustrated by an example like `ls ../data`
- Figure 8. Oh boy. If I didn't have a bunch of deadlines, I would be so tempted to help you out here! I can give you this OmniGraffle source...!
  ![Screen Shot 2013-04-09 at 15 10 04 ](https://f.cloud.github.com/assets/871533/359499/3c5353a8-a162-11e2-928d-c8460520163f.png)
- Question 2 under Figure 8 challenges is confusing because that result is not consistent with the figure. Maybe it should come before the diagram...
- "Nano is a very simple text editor that only a programmer could really love." Throwaway line that is not really true. Programmers don't love it. Similar on the "Great power comes great responsibility line"
- Pipes and filters. Seems like wildcards could come a bit earlier
- Typo: you switch between calling her program `goostat` and `goostats`
- For the xylose.dat challenge, it is probably a good idea to call the output file with an extension that won't match *.dat...
- Below that, in challenge 3, the left right business seems unnecessarily obfuscatory. People have enough trouble figuring out what are special words and what are just arbitrary variable names.
- Unnumbering: instead of introducing `colrm` maybe show how to use `cut` (already introduced) to do the same thing...
- It should probably have anchor tags for the subsections, so people could go to/bookmark/share certain sections. It is a long document not to have any bookmarks along the way.
- The binary files box seems like it is just stuck there w/o much relevance to the surroundings.
- In the goodiff example (I like that you move the stat to the front of the line instead of sorting out `sort -k`) it might be worth point out that the `\` MUST be the last character on the line, with no space after since is escaping the return character...

**Comment by katieirenec** [comment]
I think you've gotta keep those humorous lines about nano and responsibility. Humor is important for keeping people interested, it's not a "throwaway". Wouldn't a slide with Spiderman get everyone's attention?

![image](https://f.cloud.github.com/assets/3497707/365093/172dff9c-a234-11e2-859a-24549ac64dca.png)

**Comment by beroe** [comment]
Agree about humor and informal tone in general. I'm fine with the rest of the quips, but the nano line is patently false. I was just too nice to say it. :^) Emacs and VIM are editors only a programmer could love, not nano.

In my experience, the spiderman quote (apparently originally Voltaire) is way overused.

**Comment by amyrhoda** [comment]
What about "Nano is an editor only a programmer could love -- and even they don't." Are we allowed to use Spiderman? Those other monsters were handcrafted just for us, you know!
